### ISSUE TITLE
clay_tip_calculator.py question

### ISSUE THREAD

**Issue by tortoro** [TheDeepEnd/python-snippets#1]
How do you make functions in python? I'm not sure I understand where that's happening, there's no {} or anything.

Also I noticed the program does weird things if I don't put in float values for the input, what up?

**Comment by TylerNakamura** [comment]
Please read [python basics - functions](https://en.wikibooks.org/wiki/Python_Programming/Functions) for more about how functions work in python.

And please don't put non floats in, as that is not how the program is not intended to work

**Comment by tortoro** [comment]
``` bash
python-snippets - tor $ python clay_tip_calculator.py
Please enter the total amount as a float: hello
Traceback (most recent call last):
  File "clay_tip_calculator.py", line 10, in <module>
    calculateTip()
  File "clay_tip_calculator.py", line 4, in calculateTip
    total = float(input("Please enter the total amount as a float: "))
  File "<string>", line 1, in <module>
NameError: name 'hello' is not defined
```

I think I broke your program.

**Comment by TylerNakamura** [comment]
I told you to only put floats

**Comment by TylerNakamura** [comment]
This is a snippet not a fully functional program
